server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ajayonlineforu/config-server-example
          search-paths:
           - '*service'
          #username: root
          #passphrase: 12345